# Generated by Django 4.2.25 on 2025-10-15 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(blank=True, max_length=20)),
                ('nama_lengkap', models.CharField(max_length=200)),
                ('alamat', models.CharField(blank=True, max_length=255)),
                ('no_telepon', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pengaduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('BARU', 'Baru'), ('DIPROSES', 'Diproses'), ('SELESAI', 'Selesai')], default='BARU', max_length=10)),
                ('tanggal_lapor', models.DateTimeField(auto_now_add=True)),
                ('pelapor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengaduan', to='warga.warga')),
            ],
        ),
    ]
